# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'op_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_opDialogBase(object):
    def setupUi(self, opDialogBase):
        opDialogBase.setObjectName("opDialogBase")
        opDialogBase.resize(398, 262)
        self.label = QtWidgets.QLabel(opDialogBase)
        self.label.setGeometry(QtCore.QRect(20, 60, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(opDialogBase)
        self.comboBox.setGeometry(QtCore.QRect(110, 60, 181, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.label_2 = QtWidgets.QLabel(opDialogBase)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(opDialogBase)
        self.comboBox_2.setGeometry(QtCore.QRect(110, 110, 181, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton = QtWidgets.QPushButton(opDialogBase)
        self.pushButton.setGeometry(QtCore.QRect(310, 60, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(opDialogBase)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 110, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(opDialogBase)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 220, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(opDialogBase)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox_3 = QtWidgets.QComboBox(opDialogBase)
        self.comboBox_3.setGeometry(QtCore.QRect(110, 160, 181, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.pushButton_4 = QtWidgets.QPushButton(opDialogBase)
        self.pushButton_4.setGeometry(QtCore.QRect(310, 160, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(opDialogBase)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 401, 41))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("head.png"))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(opDialogBase)
        QtCore.QMetaObject.connectSlotsByName(opDialogBase)

    def retranslateUi(self, opDialogBase):
        _translate = QtCore.QCoreApplication.translate
        opDialogBase.setWindowTitle(_translate("opDialogBase", "op"))
        self.label.setText(_translate("opDialogBase", "LOCATION"))
        self.label_2.setText(_translate("opDialogBase", "ASSETS"))
        self.pushButton.setText(_translate("opDialogBase", "UPDATE"))
        self.pushButton_2.setText(_translate("opDialogBase", "UPDATE"))
        self.pushButton_3.setText(_translate("opDialogBase", "ALL"))
        self.label_3.setText(_translate("opDialogBase", "JOB NO"))
        self.pushButton_4.setText(_translate("opDialogBase", "UPDATE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    opDialogBase = QtWidgets.QDialog()
    ui = Ui_opDialogBase()
    ui.setupUi(opDialogBase)
    opDialogBase.show()
    sys.exit(app.exec_())

